services:
  db:
    env_file:
      - .env.prod

  odoo:
    build:
      context: .
      target: prod
    env_file:
      - .env.prod
    command: >
      /app/entrypoint.sh --proxy-mode=True

    ports:
      - "8069:8069"
    restart: always
