from . import hr_employee_inherit
from . import hrmis_service_history
from . import hrmis_training_record
from . import hrmis_district
from . import hrmis_facility_type
from . import res_users_inherit
from . import hrmis_final_profile_request
from . import hrmis_cadre
from . import hrmis_designations
from . import hrmis_health_care_unit
from . import hrmis_facility_designation